
services:
  bl3auto:
    build: .
    command: ["go", "run", "cmd/main.go", "-e", "${BL3_EMAIL}", "-p", "${BL3_PASSWORD}"]
    volumes:
      - './codes:/root/.config/bl3auto/bl3auto'

volumes:
  codes:
